sudo: required
dist: xenial
arch:
  - arm64
  - amd64
env:
 - USE_CACHE=true TRAVIS_PIPELINE=docker
 - USE_CACHE=true TRAVIS_PIPELINE=buildah BUILDAH_LAYERS=true

language: go

go:
 - 1.13.x

services: docker

install:
 - [[ "${TRAVIS_PIPELINE}" == "buildah" ]] && ./.travis/install_buildah.sh
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

script:
  - ./run_uts.sh
  - $GOPATH/bin/goveralls -coverprofile=ut/coverage/coverage3.out -service=travis-ci -repotoken ZY6MA490QABNKGnJgYLi53QTDuTC4H69K
