apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenantconfigs.danm.k8s.io
spec:
  scope: Cluster
  group: danm.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: TenantConfig
    plural: tenantconfigs
    singular: tenantconfig
    shortNames:
    - tc
    - tconf
    categories:
    - all
