name: "Minikube workflow"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Minikube
      id: minikube
      uses: CodingNagger/minikube-setup-action@v1.0.2
    - name: Launch Minikube
      run: eval ${{ steps.minikube.outputs.launcher }}
    - name: Check pods
      run: |
        kubectl get pods -A -o wide
        kubectl get nodes -o wide
